spring:
  application:
    name: petstorepetservice
  datasource:
    url: jdbc:postgresql://${POSTGRES_PET_URL:localhost}:${DATABASE_PET_PORT:5432}/${DATABASE_PET_name:petstorepetservice_db}
    username: ${POSTGRES_PET_USER:postgres}
    password: ${POSTGRES_PET_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_PET_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: never

server:
  port: ${PETSTOREPETSERVICE_SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    ssl:
      enabled: false
    diskspace:
      enabled: false
